name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX Action
        uses: fudan-mse/latex-action@v0.0.1
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: main.pdf
